-- TODO: Make parrots-of-paradise just like this, but also add flake.nix
return {
  -- {
  --   "folke/tokyonight.nvim", -- `:Telescope colorscheme`.
  --   priority = 1000, -- Make sure to load this before all the other start plugins.
  --   init = function() -- Load the colorscheme here.
  --     vim.cmd.colorscheme("tokyonight-night") -- Like many other themes, this one has different styles: 'tokyonight-storm', 'tokyonight-moon', or 'tokyonight-day'.
  --     vim.cmd.hi("Comment gui=none") -- You can configure highlights by doing something like:
  --   end,
  -- },

  -- {
  --   lazy = false,
  --   priority = 1000,
  --   dir = "~/plugins/colorbuddy.nvim",
  --   config = function()
  --     vim.cmd.colorscheme "gruvbuddy"
  --   end,
  -- },
  -- "rktjmp/lush.nvim",
  -- "tckmn/hotdog.vim",
  -- "dundargoc/fakedonalds.nvim",
  -- "craftzdog/solarized-osaka.nvim",
  -- { "rose-pine/neovim", name = "rose-pine" },
  -- "eldritch-theme/eldritch.nvim",
  -- "jesseleite/nvim-noirbuddy",
  -- "vim-scripts/MountainDew.vim",
  -- "miikanissi/modus-themes.nvim",
  -- "rebelot/kanagawa.nvim",
  -- "gremble0/yellowbeans.nvim",
  -- "rockyzhang24/arctic.nvim",
  -- "folke/tokyonight.nvim",
  -- "Shatur/neovim-ayu",
  -- "RRethy/base16-nvim",
  -- "xero/miasma.nvim",
  -- "cocopon/iceberg.vim",
  -- "kepano/flexoki-neovim",
  -- "ntk148v/komau.vim",
  -- { "catppuccin/nvim", name = "catppuccin" },
  -- "uloco/bluloco.nvim",
  -- "LuRsT/austere.vim",
  -- "ricardoraposo/gruvbox-minor.nvim",
  -- "NTBBloodbath/sweetie.nvim",
  -- {
  --   "maxmx03/fluoromachine.nvim",
  --   -- config = function()
  --   --   local fm = require "fluoromachine"
  --   --   fm.setup { glow = true, theme = "fluoromachine" }
  --   -- end,
  -- },
}
