#!/usr/bin/env bash
set -e 

config="${XDG_CONFIG_HOME}/alacritty/alacritty.toml"

switch_colors() {
  sed -i "s/$1/__TMP__/g ; s/$2/$1/g ; s/__TMP__/$2/g" "$config"
}

# TODO: make foreground more white

switch_colors foreground background
# switch_colors white black
# switch_colors cyan red 
# switch_colors magenta green 
# switch_colors blue yellow


# battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
# if [ $battery_level -le 10 ]
# then
#     notify-send "Battery low" "Battery level is ${battery_level}%!"
# fi
base10: "666666" # Dark grey
base11: "333333" # Darker grey
