#!/usr/bin/env bash

# Function to get CPU percentage
get_cpu_percent() {
    cpu_percent=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')
    cpu_percent_int=$(printf "%.0f" "$cpu_percent")
    echo "$cpu_percent_int"
}

# Function to get load average in GHz
get_load_average() {
    load_average=$(uptime | awk -F'[a-z]:' '{ print $2 }' | awk -F, '{print $1}' | awk '{$1=$1};1')
    printf "%.2f" "$load_average"
}

main() {
    cpu_percent=$(get_cpu_percent)
    load_average=$(get_load_average)

    echo "💻 $cpu_percent% [$load_average GHz]"
}

main
