# TODO: builtins.replaceString for ricing and maybe do URL Launcher
# TODO: Make copy/paste work(without vim mode) [wl-copy, wl-paste]
[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "2"

[font]
size = 10.2 # 8.5 # 6.5 prev

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "ExtraBold"

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Medium"

# [font.italic]
# family = "NotoSans NF Med"
# style = "Medium Italic"
# [font.italic_bold]
# family = "NotoSans NF ExtBd"
# style = "ExtraBold Italic"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#101818"
bright_foreground = "#ffffff"
foreground = "#eaeaea"

[colors.cursor]
cursor = "#993F0B"
text = "#E6E1C4"

[colors.normal]
black = "#263238"
blue = "#89ddff"
cyan = "#80cbc4"
green = "#00A600"
magenta = "#82aaff"
red = "#ec5f67"
white = "#cdd3de"
yellow = "#ffcc00"

[colors.bright]
black = "#707880"
blue = "#89ddff"
cyan = "#80cbc4"
green = "#00D900"
magenta = "#82aaff"
red = "#ec5f67"
white = "#ffffff"
yellow = "#ffcc00"

[selection]
save_to_clipboard = true

[shell]
args = ["a"]
program = "tmux"

# TODO: Check/test all these bindings
# TODO: Make tmux bindings passthrough via Alt + / and defined in alacritty

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

# [[keyboard.bindings]]
# action = "Copy"
# key = "Copy"

# [[keyboard.bindings]]
# action = "Paste"
# key = "Paste"

[[keyboard.bindings]]
key = "N"
mods = "Alt"
command = { program = "alacritty" }

[[keyboard.bindings]]
key = "W"
mods = "Alt"
command = { program = "tmux", args = ["kill-window"] }

[[keyboard.bindings]]
key = "T"
mods = "Alt"
command = { program = "tmux", args = ["new-window"] }

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "1"] }

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "2"] }

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "3"] }

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "4"] }

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "5"] }

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "6"] }

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "7"] }

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "8"] }

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t", "9"] }

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t:-"] }

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt"
command = { program = "tmux", args = ["select-window", "-t:+"] }

[[keyboard.bindings]]
key = "H"
mods = "Alt"
command = { program = "tmux", args = ["select-pane", "-L"] }

[[keyboard.bindings]]
key = "J"
mods = "Alt"
command = { program = "tmux", args = ["select-pane", "-D"] }

[[keyboard.bindings]]
key = "K"
mods = "Alt"
command = { program = "tmux", args = ["select-pane", "-U"] }

[[keyboard.bindings]]
key = "L"
mods = "Alt"
command = { program = "tmux", args = ["select-pane", "-R"] }

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
command = { program = "tmux", args = ["setw", "synchronize-panes"] }

[[keyboard.bindings]]
chars = "\u0001z"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u0001["
key = "LBracket"
mods = "Control"

# [[keyboard.bindings]]
# key = "K"
# mods = "Control"
# action = "ClearHistory"

[[keyboard.bindings]]
key = "P"
mods = "Alt"
command = { program = "tmux", args = ["kill-pane"] }
