# TODO: builtins.replaceString for ricing and maybe do URL Launcher
# TODO: Make copy/paste work(without vim mode).
[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "2"

[font]
size = 10.2 # 8.5 # 6.5 prev

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "ExtraBold"

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Medium"
# italic:
#   family: "NotoSans NF Med"
#   style: "Medium Italic"
# italic_bold:
#   family: "NotoSans NF ExtBd"
#   style: "ExtraBold Italic"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#101818"
bright_foreground = "#ffffff"
foreground = "#eaeaea"

[colors.cursor]
cursor = "#993F0B"
text = "#E6E1C4"

[colors.normal]
black = "#263238"
blue = "#89ddff"
cyan = "#80cbc4"
green = "#00A600"
magenta = "#82aaff"
red = "#ec5f67"
white = "#cdd3de"
yellow = "#ffcc00"

[colors.bright]
black = "#707880"
blue = "#89ddff"
cyan = "#80cbc4"
green = "#00D900"
magenta = "#82aaff"
red = "#ec5f67"
white = "#ffffff"
yellow = "#ffcc00"

[[colors.indexed_colors]]
color = "#ea9560"
index = 16

[[colors.indexed_colors]]
color = "#ec5f67"
index = 17

[[colors.indexed_colors]]
color = "#2c393f"
index = 18

[[colors.indexed_colors]]
color = "#37474f"
index = 19

[[colors.indexed_colors]]
color = "#c9ccd3"
index = 20

[[colors.indexed_colors]]
color = "#d5dbe5"
index = 21

[selection]
save_to_clipboard = true

[shell]
args = ["a"]
program = "tmux"

[hints.enabled.binding]
key = "U"
mods = "Alt"

# TODO: Check/test all these bindings

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Alt"

[keyboard.bindings.command]
program = "alacritty"

[[keyboard.bindings]]
key = "W"
mods = "Alt"

[keyboard.bindings.command]
args = ["kill-window"]
program = "tmux"

[[keyboard.bindings]]
key = "T"
mods = "Alt"

[keyboard.bindings.command]
args = ["new-window"]
program = "tmux"

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "1"]
program = "tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "2"]
program = "tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "3"]
program = "tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "4"]
program = "tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "5"]
program = "tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "6"]
program = "tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "7"]
program = "tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "8"]
program = "tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t", "9"]
program = "tmux"

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t:-"]
program = "tmux"

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-window", "-t:+"]
program = "tmux"

[[keyboard.bindings]]
key = "H"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-pane", "-L"]
program = "tmux"

[[keyboard.bindings]]
key = "J"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-pane", "-D"]
program = "tmux"

[[keyboard.bindings]]
key = "K"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-pane", "-U"]
program = "tmux"

[[keyboard.bindings]]
key = "L"
mods = "Alt"

[keyboard.bindings.command]
args = ["select-pane", "-R"]
program = "tmux"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"

[keyboard.bindings.command]
args = ["setw", "synchronize-panes"]
program = "tmux"

[[keyboard.bindings]]
chars = "\u0001z"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u0001["
key = "LBracket"
mods = "Control"
# - { key: K, mods: Control, action: ClearHistory }
# - { key: P,        mods: Alt, command: { program: "tmux", args: ["kill-pane"] } }
