#!/usr/bin/env bash

# NOTE: Dependency: acpi
# label = " {{5000:cat /sys/class/power_supply/BAT0/capacity}}% [{{5000:cat /sys/class/power_supply/BAT0/status}}]"

shorten_time_format() {
	local time_format=$1
	local hours=$(echo $time_format | awk -F':' '{print $1}')
	local minutes=$(echo $time_format | awk -F':' '{print $2}')
	local seconds=$(echo $time_format | awk -F':' '{print $3}')

	# Shorten the format:
	if [ "$hours" != "00" ]; then
		echo "${hours}h ${minutes}m"
	elif [ "$minutes" != "00" ]; then
		echo "${minutes}m ${seconds}s"
	else
		echo "${seconds}s"
	fi
}

get_battery_status() {
	battery_percent=$(acpi -b | grep -P -o '[0-9]+(?=%)')
	battery_status=$(acpi -b | grep -o "Charging\|Discharging")

	get_battery_icon() {
		if [ $battery_percent -gt 90 ]; then
			echo ""
		elif [ $battery_percent -gt 70 ]; then
			echo ""
		elif [ $battery_percent -gt 50 ]; then
			echo ""
		elif [ $battery_percent -gt 30 ]; then
			echo ""
		else
			echo ""
		fi
	}

	if [ "$battery_status" == "Charging" ]; then
		if [ "$battery_percent" -eq 100 ]; then
			echo "$(get_battery_icon) $battery_percent%"
			return
		fi
		time_to_full=$(acpi -b | grep -o -P '(\d+:\d+:\d+|\d+:\d+|\d+\s(?:minute|min|hour|h))' | head -1)
		if [ -z "$time_to_full" ]; then
			echo "z$(get_battery_icon) $battery_percent% [Calculating]"
		else
			time_to_full_short=$(shorten_time_format "$time_to_full")
			echo "$(get_battery_icon) $battery_percent% [$time_to_full_short]"
		fi
	else
		time_to_empty=$(acpi -b | grep -o -P '(\d+:\d+:\d+|\d+:\d+|\d+\s(?:minute|min|hour|h))' | head -1)
		if [ -z "$time_to_empty" ]; then
			echo "$(get_battery_icon) $battery_percent% [Calculating]"
		else
			time_to_empty_short=$(shorten_time_format "$time_to_empty")
			echo "$(get_battery_icon) $battery_percent% [$time_to_empty_short]"
		fi

	fi
}

get_battery_status














# battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
# if [ $battery_level -le 10 ]
# then
#     notify-send "Battery low" "Battery level is ${battery_level}%!"
# fi

# notify-send hints: https://unix.stackexchange.com/questions/251243/what-do-a-notify-send-notification-category-hint-and-version-parameters-mean

# while true; do
#     export DISPLAY=:0.0
#
#     while read line; do
#         value=$(echo $line | sed 's/%//g' | cut -d " " -f 2)
#         key=$(echo $line | sed 's/%//g' | cut -d ":" -f 1)
#
#         if [ $key = 'state' ]; then
#             bat_state=$value
#         else
#             bat_percent=$value
#         fi
#     done < <(upower -i $(upower -e | grep BAT) | grep -E "percentage|state")
#
#     if [ $bat_state == 'discharging' ]; then
#         if [ $bat_percent -lt 30 ]; then
#             dunstify --urgency=CRITICAL "Battery Low" "Level: ${bat_percent}%"
#             paplay /usr/share/sounds/freedesktop/stereo/suspend-error.oga
#         fi
#     else
#         if [ $bat_percent -ge 100 ]; then
#             dunstify --urgency=NORMAL "Battery Full" "Level: ${bat_percent}%"
#         fi
#     fi
#
#     sleep 10
# done
