[manager]
prepend_keymap = [
  { on = [
    "e",
  ], run = "shell --confirm --block 'nvim $0'", desc = "Edit file" },
  { on = [
    "<C-k>",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "<C-j>",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = [
    "?",
  ], run = "help", desc = "Open help" },
  { on = [
    "K",
  ], run = "seek -1", desc = "Seek up 1 units in the preview" },
  { on = [
    "J",
  ], run = "seek 1", desc = "Seek down 1 units in the preview" },
  { on = [
    "T",
  ], run = "plugin --sync max-preview", desc = "Make Preview Fullscreen" },
  { on = [
    "<C-n>",
  ], exec = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
''' },

  # NOTE: This was buggy, make this work in future versions of yazi:
  #  { on = [
  #    "c",
  #    "S",
  #  ], run = [
  #    "yank",
  #    '''
  # shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
  #       ''',
  #  ], desc = "Copy selected files to the system clipboard" },
]

[input]
append_keymap = [{ on = ["?"], run = "help", desc = "Open help" }]


[completion]
prepend_keymap = [
  { on = [
    "<C-k>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<C-j>",
  ], run = "arrow 1", desc = "Move cursor down" },
  { on = [
    "?",
  ], run = "help", desc = "Open help" },
]

[help]
append_keymap = [
  { on = [
    "<C-k>",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "<C-j>",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
]
