return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "deno",
        "ruby-lsp",
        "rust-analyzer",
        "ansible-language-server",
        "ansible-lint",
        "codelldb",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "elixir-ls",
        "ember-language-server",
        "erlang-debugger",
        "erlang-ls",
        "gitui",
        "hadolint",
        "helm-ls",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "shfmt",
        "solargraph",
        "solidity",
        "stylua",
        "taplo",
        "typescript-language-server",
        "yaml-language-server",
      },
    },
  },
}
