#!/bin/bash

# Function to get memory percentage
get_memory_percent() {
    memory_percent=$(free | awk '/Mem:/ {print ($3/$2)*100}')
    printf "%.1f" "$memory_percent"
}

# Function to get memory used in GB
get_memory_used() {
    memory_used=$(free -h | awk '/Mem:/ {print $3}' | cut -d 'G' -f 1)
    printf "%.2f" "$memory_used"
}

# Function to get total memory in GB
get_memory_total() {
    memory_total=$(free -h | awk '/Mem:/ {print $2}' | cut -d 'G' -f 1)
    printf "%.2f" "$memory_total"
}

main() {
    memory_percent=$(get_memory_percent)
    memory_used=$(get_memory_used)
    memory_total=$(get_memory_total)

    echo "📟 $memory_percent% [$memory_used GB / $memory_total GB]"
}

main
